version: '3.8'

services:
  web:
    build: .
    container_name: directory_viewer_challenge
    ports:
      - "8080:80"
    volumes:
      - ./command_injection.php:/var/www/html/command_injection.php
    restart: unless-stopped
